

DEBUG=True

# DB_USERNAME='root'
# DB_PASSWORD='admin'
# DB_HOST='127.0.0.1'
# DB_PORT='3306'
# DB_NAME='zlbbs'
# HOSTNAME='localhost'
# DATABASE='csws2'
# USERNAME='root'
# PASSWORD='admin'
# SQLALCHEMY_DATABASE_URI = 'mysql://{}:{}@{}/{}'.format(USERNAME,PASSWORD,HOSTNAME,DATABASE)\HOSTNAME='localhost'
DATABASE='mybbs'
USERNAME='root'
PASSWORD='admin'
HOSTNAME='127.0.0.1'
DB_URI = 'mysql://{}:{}@{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,DATABASE)


SQLALCHEMY_DATABASE_URI=DB_URI
# SQLALCHEMY_TRACK_MODIFICATIONS=False ###
SQLALCHEMY_TRACK_MODIFICATIONS=True ###
